const ReservationActionTypes = {
  GET_RESERVATIONS_START: "GET_RESERVATIONS_START",
  GET_RESERVATIONS_SUCCESS: "GET_RESERVATIONS_SUCCESS",
  GET_RESERVATIONS_FAILURE: "GET_RESERVATIONS_FAILURE",
  CREATE_RESERVATION_START: "CREATE_RESERVATION_START",
  CREATE_RESERVATION_SUCCESS: "CREATE_RESERVATION_SUCCESS",
  CREATE_RESERVATION_FAILURE: "CREATE_RESERVATION_FAILURE",
  UPDATE_RESERVATION_START: "UPDATE_RESERVATION_START",
  UPDATE_RESERVATION_SUCCESS: "UPDATE_RESERVATION_SUCCESS",
  UPDATE_RESERVATION_FAILURE: "UPDATE_RESERVATION_FAILURE",
  DELETE_RESERVATION_START: "DELETE_RESERVATION_START",
  DELETE_RESERVATION_SUCCESS: "DELETE_RESERVATION_SUCCESS",
  DELETE_RESERVATION_FAILURE: "DELETE_RESERVATION_FAILURE",
};

export default ReservationActionTypes;