const TableActionTypes = {
  GET_TABLES_START: "GET_TABLES_START",
  GET_TABLES_SUCCESS: "GET_TABLES_SUCCESS",
  GET_TABLES_FAILURE: "GET_TABLES_FAILURE",
  CREATE_TABLE_START: "CREATE_TABLE_START",
  CREATE_TABLE_SUCCESS: "CREATE_TABLE_SUCCESS",
  CREATE_TABLE_FAILURE: "CREATE_TABLE_FAILURE",
  UPDATE_TABLE_START: "UPDATE_TABLE_START",
  UPDATE_TABLE_SUCCESS: "UPDATE_TABLE_SUCCESS",
  UPDATE_TABLE_FAILURE: "UPDATE_TABLE_FAILURE",
  DELETE_TABLE_START: "DELETE_TABLE_START",
  DELETE_TABLE_SUCCESS: "DELETE_TABLE_SUCCESS",
  DELETE_TABLE_FAILURE: "DELETE_TABLE_FAILURE",
};

export default TableActionTypes;
